version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      actions:
        patterns: [ "*" ]

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      npm-deps:
        patterns: [ "*" ]
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]

  - package-ecosystem: uv
    directory: /backend
    schedule:
      interval: monthly
    groups:
      uv-deps:
        patterns: [ "*" ]
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
