name: 'Setup Node and pnpm'
description: 'Sets up Node.js and prepares pnpm via Corepack.'
runs:
  using: 'composite'
  steps:
    - name: Set up pnpm and Node.js
      uses: pnpm/setup@v2
      with:
        runtime: node@${{ inputs.node-version }}
        cache: true
        cache-dependency-path: pnpm-lock.yaml
        install: false

inputs:
  node-version:
    description: 'Node.js version'
    required: false
    default: '26'
