"""Initial state

Revision ID: 490d0308e138
Revises: 
Create Date: 2026-04-04 20:23:12.239794

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "490d0308e138"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("categories",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("slug", sa.String(length=100), nullable=True),
    sa.Column("difficulty", sa.String(length=20), nullable=False),
    sa.Column("default_locale", sa.String(length=16), nullable=False),
    sa.Column("source", sa.String(length=20), nullable=False),
    sa.Column("available_locales", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index("idx_category_available_locales", "categories", ["available_locales"], unique=False, postgresql_using="gin")
    op.create_index("idx_category_difficulty", "categories", ["difficulty"], unique=False)
    op.create_index("idx_category_slug", "categories", ["slug"], unique=False)
    op.create_table("prompts",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("stable_key", sa.String(length=100), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("stable_key")
    )
    op.create_index("idx_prompt_stable_key", "prompts", ["stable_key"], unique=False)
    op.create_table("users",
    sa.Column("id", sa.String(length=32), nullable=False),
    sa.Column("username", sa.String(length=40), nullable=False),
    sa.Column("display_name", sa.String(length=80), nullable=True),
    sa.Column("preferred_locale", sa.String(length=16), nullable=False),
    sa.Column("password_hash", sa.String(length=255), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("username")
    )
    op.create_index("idx_users_preferred_locale", "users", ["preferred_locale"], unique=False)
    op.create_index("idx_users_username", "users", ["username"], unique=True)
    op.create_table("category_prompts",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("category_id", sa.Integer(), nullable=False),
    sa.Column("prompt_id", sa.Integer(), nullable=False),
    sa.Column("sort_order", sa.Integer(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="CASCADE"),
    sa.ForeignKeyConstraint(["prompt_id"], ["prompts.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("category_id", "prompt_id", name="uq_category_prompt")
    )
    op.create_index("idx_category_prompt_category", "category_prompts", ["category_id"], unique=False)
    op.create_index("idx_category_prompt_prompt", "category_prompts", ["prompt_id"], unique=False)
    op.create_table("category_translations",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("category_id", sa.Integer(), nullable=False),
    sa.Column("locale", sa.String(length=16), nullable=False),
    sa.Column("name", sa.String(length=100), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("category_id", "locale", name="uq_category_translation_locale")
    )
    op.create_index("idx_category_translation_locale", "category_translations", ["locale"], unique=False)
    op.create_table("prompt_translations",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("prompt_id", sa.Integer(), nullable=False),
    sa.Column("locale", sa.String(length=16), nullable=False),
    sa.Column("label", sa.String(length=100), nullable=False),
    sa.Column("aliases", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(["prompt_id"], ["prompts.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("prompt_id", "locale", name="uq_prompt_translation_locale")
    )
    op.create_index("idx_prompt_translation_locale", "prompt_translations", ["locale"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_prompt_translation_locale", table_name="prompt_translations")
    op.drop_table("prompt_translations")
    op.drop_index("idx_category_translation_locale", table_name="category_translations")
    op.drop_table("category_translations")
    op.drop_index("idx_category_prompt_prompt", table_name="category_prompts")
    op.drop_index("idx_category_prompt_category", table_name="category_prompts")
    op.drop_table("category_prompts")
    op.drop_index("idx_users_username", table_name="users")
    op.drop_index("idx_users_preferred_locale", table_name="users")
    op.drop_table("users")
    op.drop_index("idx_prompt_stable_key", table_name="prompts")
    op.drop_table("prompts")
    op.drop_index("idx_category_slug", table_name="categories")
    op.drop_index("idx_category_difficulty", table_name="categories")
    op.drop_index("idx_category_available_locales", table_name="categories", postgresql_using="gin")
    op.drop_table("categories")
    # ### end Alembic commands ###
