"""JSONB translations

Revision ID: b2a7f484d1a9
Revises: 490d0308e138
Create Date: 2026-04-04 21:15:48.405622

"""

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

if TYPE_CHECKING:
    from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "b2a7f484d1a9"
down_revision: str | None = "490d0308e138"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "categories",
        sa.Column("translations", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
    )
    op.add_column(
        "prompts",
        sa.Column("translations", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
    )

    # DATA MIGRATION
    op.execute("""
    UPDATE categories
    SET translations = COALESCE((
        SELECT jsonb_object_agg(locale, jsonb_build_object('name', name))
        FROM category_translations
        WHERE category_translations.category_id = categories.id
    ), '{}'::jsonb);
    """)

    op.execute("""
    UPDATE prompts
    SET translations = COALESCE((
        SELECT jsonb_object_agg(locale, jsonb_build_object('label', label, 'aliases', COALESCE(aliases, '[]'::jsonb)))
        FROM prompt_translations
        WHERE prompt_translations.prompt_id = prompts.id
    ), '{}'::jsonb);
    """)

    op.create_index("idx_category_translations", "categories", ["translations"], unique=False, postgresql_using="gin")
    op.create_index("idx_prompt_translations", "prompts", ["translations"], unique=False, postgresql_using="gin")

    op.drop_index(op.f("idx_category_translation_locale"), table_name="category_translations")
    op.drop_table("category_translations")
    op.drop_index(op.f("idx_prompt_translation_locale"), table_name="prompt_translations")
    op.drop_table("prompt_translations")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_prompt_translations", table_name="prompts", postgresql_using="gin")
    op.drop_column("prompts", "translations")
    op.drop_index("idx_category_translations", table_name="categories", postgresql_using="gin")
    op.drop_column("categories", "translations")
    op.create_table(
        "prompt_translations",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("prompt_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("locale", sa.VARCHAR(length=16), autoincrement=False, nullable=False),
        sa.Column("label", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("aliases", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["prompt_id"], ["prompts.id"], name=op.f("prompt_translations_prompt_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("prompt_translations_pkey")),
        sa.UniqueConstraint(
            "prompt_id",
            "locale",
            name=op.f("uq_prompt_translation_locale"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(op.f("idx_prompt_translation_locale"), "prompt_translations", ["locale"], unique=False)
    op.create_table(
        "category_translations",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("category_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("locale", sa.VARCHAR(length=16), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"], ["categories.id"], name=op.f("category_translations_category_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("category_translations_pkey")),
        sa.UniqueConstraint(
            "category_id",
            "locale",
            name=op.f("uq_category_translation_locale"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(op.f("idx_category_translation_locale"), "category_translations", ["locale"], unique=False)
    # ### end Alembic commands ###
